name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Кэширование зависимостей Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('*/*.gradle*', '*/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Сборка проекта и запуск тестов
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      # Генерация отчетов Allure (предполагается, что в проекте уже настроена интеграция с Allure)
      - name: Generate Allure report
        run: ./gradlew allureReport

      # Публикация отчетов Allure на GitHub Pages или другой платформе
      # Этот шаг может потребовать дополнительной настройки в зависимости от платформы
      - name: Publish Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: build/reports/allure-report

    # Дополнительно можно добавить шаги для интеграции с другими сервисами отчетов о тестировании
